version: '3.7'

services:
  web:
    build: .
    container_name: expressjscontainer
    restart: always
    command: npm start
    volumes:
      - .:/code
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:5.7 
    container_name: mysqlcontainer
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uptasknode
      MYSQL_USER: setcain
      MYSQL_PASSWORD: SuperSecret
